# ==============================================================================
# TENSORFLOW.JS TO ARDUINO CONVERTER - COMPLETE PIPELINE
#
# This script performs the complete conversion pipeline for deploying ML models
# on Arduino/microcontrollers:
#   1. TensorFlow.js (model.json + weights) -> Keras (.h5)
#   2. Keras (.h5) -> TensorFlow Lite (.tflite)
#   3. TensorFlow Lite (.tflite) -> C Header (.h) using xxd
#
# Arguments (received from the Node.js bridge via run_converter.sh):
#   sys.argv[1]: Input Folder Path (WSL path to the TF.js model directory)
#   sys.argv[2]: Output File Path (WSL path where the final .h5 file should be saved)
#   sys.argv[3]: Model Name (The expected name of the model for logging)
#
# Usage (called by run_converter.sh):
# python3 model_converter.py <input_path> <output_path> <model_name>
# ==============================================================================

import sys
import os
import subprocess

# Set environment variable to suppress non-critical TensorFlow logs
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import tensorflowjs as tfjs


def convert_keras_to_tflite(h5_path, tflite_path):
    """
    Converts a Keras .h5 model to TensorFlow Lite format.
    
    :param h5_path: Path to the input Keras .h5 file.
    :param tflite_path: Path to the output .tflite file.
    :return: True if successful, False otherwise.
    """
    print(f"Python: Converting Keras model to TFLite...")
    print(f"Python: Input H5: {h5_path}")
    print(f"Python: Output TFLite: {tflite_path}")
    
    try:
        # Load the Keras model
        model = tf.keras.models.load_model(h5_path)
        print(f"Python: Keras model loaded successfully")
        
        # Convert to TFLite
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        
        # Optional: Add optimizations for smaller size (quantization)
        # This reduces model size and increases inference speed on microcontrollers
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        
        # Optional: Set supported operations for microcontrollers
        # Uncomment if you need specific ops for Arduino/embedded devices
        # converter.target_spec.supported_ops = [
        #     tf.lite.OpsSet.TFLITE_BUILTINS_INT8
        # ]
        
        print(f"Python: Converting to TFLite format...")
        tflite_model = converter.convert()
        
        # Save the TFLite model
        with open(tflite_path, 'wb') as f:
            f.write(tflite_model)
        
        tflite_size_kb = len(tflite_model) / 1024.0
        print(f"Python: TFLite model created successfully ({tflite_size_kb:.2f} KB)")
        
        return True
        
    except Exception as e:
        print(f"Python ERROR: TFLite conversion failed: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return False


def convert_tflite_to_c_header(tflite_path, header_path, array_name):
    """
    Converts a .tflite file to a C header file using xxd.
    
    :param tflite_path: Path to the .tflite file.
    :param header_path: Path to the output .h file.
    :param array_name: Name for the C array variable.
    :return: True if successful, False otherwise.
    """
    print(f"Python: Converting TFLite to C header...")
    print(f"Python: Input TFLite: {tflite_path}")
    print(f"Python: Output Header: {header_path}")
    print(f"Python: Array name: {array_name}")
    
    try:
        # Use xxd command to generate C array
        # xxd -i creates a C include file with the binary data as an array
        result = subprocess.run(
            ['xxd', '-i', tflite_path],
            capture_output=True,
            text=True,
            check=True
        )
        
        # Get the output from xxd
        c_array = result.stdout
        
        # xxd generates variable names based on the filename
        # We'll customize it to use our desired array name
        original_name = os.path.basename(tflite_path).replace('.', '_').replace('-', '_')
        c_array = c_array.replace(original_name, array_name)
        
        # Write to header file
        with open(header_path, 'w') as f:
            # Add header guard and additional info
            guard_name = f"{array_name.upper()}_H"
            f.write(f"// Auto-generated C header from {os.path.basename(tflite_path)}\n")
            f.write(f"// Generated by model_converter.py\n\n")
            f.write(f"#ifndef {guard_name}\n")
            f.write(f"#define {guard_name}\n\n")
            f.write(c_array)
            f.write(f"\n#endif // {guard_name}\n")
        
        header_size_kb = os.path.getsize(header_path) / 1024.0
        print(f"Python: C header file created successfully ({header_size_kb:.2f} KB)")
        
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"Python ERROR: xxd command failed: {e.stderr}", file=sys.stderr)
        print(f"Python ERROR: Make sure 'xxd' is installed (usually comes with vim)", file=sys.stderr)
        return False
    except Exception as e:
        print(f"Python ERROR: C header generation failed: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return False


def convert_tfjs_to_arduino(input_path, output_path, model_name):
    """
    Complete conversion pipeline: TF.js -> Keras -> TFLite -> C Header
    
    :param input_path: Path to the directory containing model.json.
    :param output_path: Base output path for the .h5 file (will also generate .tflite and .h).
    :param model_name: The model name (used for file naming and array naming).
    """
    
    print(f"Python: ========================================")
    print(f"Python: STARTING COMPLETE CONVERSION PIPELINE")
    print(f"Python: ========================================")
    print(f"Python: Model name: {model_name}")
    print(f"Python: Input folder: {input_path}")
    print(f"Python: Output base path: {output_path}")
    
    # Define all output paths
    output_dir = os.path.dirname(output_path)
    h5_path = output_path  # This is already the .h5 path from the argument
    tflite_path = os.path.join(output_dir, f"{model_name}.tflite")
    header_path = os.path.join(output_dir, f"{model_name}.h")
    
    try:
        # ===== STEP 1: TensorFlow.js to Keras =====
        print(f"\nPython: ========================================")
        print(f"Python: STEP 1: TensorFlow.js to Keras (.h5)")
        print(f"Python: ========================================")
        
        model_json_path = os.path.join(input_path, 'model.json')
        print(f"Python: Looking for model.json at: {model_json_path}")
        
        if not os.path.exists(model_json_path):
            print(f"Python ERROR: model.json not found at {model_json_path}")
            sys.exit(1)
        
        print(f"Python: model.json found ✓")
        
        # Create output directory if it doesn't exist
        if not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)
            print(f"Python: Created output directory: {output_dir}")
        
        print(f"Python: Loading TensorFlow.js model from {input_path}...")
        keras_model = tfjs.converters.load_keras_model(model_json_path)
        print(f"Python: TensorFlow.js model loaded successfully ✓")
        
        print(f"Python: Saving as Keras .h5 format to {h5_path}...")
        keras_model.save(h5_path)
        
        h5_size_kb = os.path.getsize(h5_path) / 1024.0
        print(f"Python: Keras model saved successfully ✓ ({h5_size_kb:.2f} KB)")
        
        # ===== STEP 2: Keras to TensorFlow Lite =====
        print(f"\nPython: ========================================")
        print(f"Python: STEP 2: Keras (.h5) to TensorFlow Lite (.tflite)")
        print(f"Python: ========================================")
        
        if not convert_keras_to_tflite(h5_path, tflite_path):
            print(f"Python ERROR: TFLite conversion failed")
            sys.exit(1)
        
        print(f"Python: TFLite conversion successful ✓")
        
        # ===== STEP 3: TensorFlow Lite to C Header =====
        print(f"\nPython: ========================================")
        print(f"Python: STEP 3: TensorFlow Lite (.tflite) to C Header (.h)")
        print(f"Python: ========================================")
        
        array_name = f"{model_name}_tflite"
        if not convert_tflite_to_c_header(tflite_path, header_path, array_name):
            print(f"Python ERROR: C header generation failed")
            sys.exit(1)
        
        print(f"Python: C header generation successful ✓")
        
        # ===== FINAL SUMMARY =====
        print(f"\nPython: ========================================")
        print(f"Python: ✓✓✓ CONVERSION PIPELINE COMPLETE ✓✓✓")
        print(f"Python: ========================================")
        print(f"Python: ")
        print(f"Python: Generated files:")
        print(f"Python:   1. Keras model:    {os.path.basename(h5_path)}")
        print(f"Python:   2. TFLite model:   {os.path.basename(tflite_path)}")
        print(f"Python:   3. C Header:       {os.path.basename(header_path)}")
        print(f"Python: ")
        
        h5_size = os.path.getsize(h5_path) / 1024.0
        tflite_size = os.path.getsize(tflite_path) / 1024.0
        header_size = os.path.getsize(header_path) / 1024.0
        
        print(f"Python: File sizes:")
        print(f"Python:   - Keras (.h5):     {h5_size:>8.2f} KB")
        print(f"Python:   - TFLite (.tflite): {tflite_size:>8.2f} KB")
        print(f"Python:   - Header (.h):      {header_size:>8.2f} KB")
        print(f"Python: ")
        print(f"Python: The C header '{os.path.basename(header_path)}' is ready to be")
        print(f"Python: included in your Arduino project!")
        print(f"Python: Array name: {array_name}")
        print(f"Python: Array length: {array_name}_len")
        print(f"Python: ========================================")
        
    except Exception as e:
        print(f"\nPython ERROR: Conversion pipeline failed: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    # sys.argv[0] is the script name itself
    if len(sys.argv) != 4:
        print(f"Python ERROR: Expected 3 arguments (input_path, output_path, model_name), but received {len(sys.argv) - 1}.", file=sys.stderr)
        print(f"Python ERROR: Usage: python3 model_converter.py <input_folder> <output_h5_path> <model_name>", file=sys.stderr)
        sys.exit(1)
    
    # Arguments received from run_converter.sh
    input_folder = sys.argv[1]
    output_file = sys.argv[2]
    model_name = sys.argv[3]
    
    convert_tfjs_to_arduino(input_folder, output_file, model_name)